name: konsi_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.5.0
  firebase_auth: ^3.11.0
  firebase_storage: ^10.3.10
  google_sign_in: ^5.4.2
  animated_splash_screen: ^1.3.0
  flutter_staggered_animations: ^1.1.1
  provider: ^6.0.3
  convex_bottom_bar: ^3.1.0+1
  flutter_platform_widgets: ^2.0.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  map_location_picker: ^1.0.2
  google_fonts: ^3.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/logo-konsi.png
     - assets/images/google-logo.png


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
